### ISSUE TITLE
Unable to build for vlc-3.0.1 STATIC on windows using mingw32

### ISSUE THREAD

**Issue by sportimization** [vlc-qt/vlc-qt#250]
I tried a STATIC build on windows using vlc-3.0.1 and the following procedure:

1. download vlc-3.0.1 sdk files
2. replace original includes in vlc-sdk with vlc-qt-files from folder libvlc-headers
3. cmake .. -DCMAKE_PREFIX_PATH="C:/Qt/Qt5.10.1/5.10.1/mingw53_32" -G"MinGW Makefiles" -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX="C:\install\vlc-qt" -DLIBVLC_LIBRARY="C:\vlc-3.0.1\sdk\lib\libvlc.lib" -DLIBVLCCORE_LIBRARY="C:\vlc-3.0.1\sdk\lib\libvlccore.lib" -DLIBVLC_INCLUDE_DIR="C:\vlc-3.0.1\sdk\include" -DSTATIC=ON
4. mingw-make.exe

Im getting the following error:

[ 71%] Linking CXX executable Test_CoreInstance.exe
cd /d C:\QtProjects\Resources\vlc-qt\vlc-qt\build\tests\core && "C:\Program Files\CMake\bin\cmake.exe" -E cmake_link_script CMakeFiles\Test_CoreInstance.dir\link.txt --verbose=1
"C:\Program Files\CMake\bin\cmake.exe" -E remove -f CMakeFiles\Test_CoreInstance.dir/objects.a
C:\Qt\Qt5.10.1\Tools\mingw530_32\bin\ar.exe cr CMakeFiles\Test_CoreInstance.dir/objects.a @CMakeFiles\Test_CoreInstance.dir\objects1.rsp
C:\Qt\Qt5.10.1\Tools\mingw530_32\bin\g++.exe -O3 -DNDEBUG   -static-libgcc -static-libstdc++  -s -Wl,--whole-archive CMakeFiles\Test_CoreInstance.dir/objects.a -Wl,--no-whole-archive  -o Test_CoreInstance.exe -Wl,--out-implib,libTest_CoreInstance.dll.a -Wl,--major-image-version,0,--minor-image-version,0 @CMakeFiles\Test_CoreInstance.dir\linklibs.rsp
CMakeFiles\Test_CoreInstance.dir/objects.a(TestInstance.cpp.obj):TestInstance.cpp:(.text+0xd7): undefined reference to `_imp___ZN9VlcCommon4argsEv'
CMakeFiles\Test_CoreInstance.dir/objects.a(TestInstance.cpp.obj):TestInstance.cpp:(.text+0xf4): undefined reference to `_imp___ZN11VlcInstanceC1ERK11QStringListP7QObject'
CMakeFiles\Test_CoreInstance.dir/objects.a(TestInstance.cpp.obj):TestInstance.cpp:(.text+0x10a): undefined reference to `_imp___ZNK11VlcInstance6statusEv'
CMakeFiles\Test_CoreInstance.dir/objects.a(TestInstance.cpp.obj):TestInstance.cpp:(.text+0x27f): undefined reference to `_imp___ZN9VlcCommon13setPluginPathERK7QString'
CMakeFiles\Test_CoreInstance.dir/objects.a(TestInstance.cpp.obj):TestInstance.cpp:(.text+0x2de): undefined reference to `_imp___ZN9VlcCommon4argsEv'
CMakeFiles\Test_CoreInstance.dir/objects.a(TestInstance.cpp.obj):TestInstance.cpp:(.text+0x2fb): undefined reference to `_imp___ZN11VlcInstanceC1ERK11QStringListP7QObject'
CMakeFiles\Test_CoreInstance.dir/objects.a(TestInstance.cpp.obj):TestInstance.cpp:(.text+0x311): undefined reference to `_imp___ZNK11VlcInstance6statusEv'
CMakeFiles\Test_CoreInstance.dir/objects.a(TestInstance.cpp.obj):TestInstance.cpp:(.text+0x423): undefined reference to `_imp___ZN9VlcCommon4argsEv'
CMakeFiles\Test_CoreInstance.dir/objects.a(TestInstance.cpp.obj):TestInstance.cpp:(.text+0x440): undefined reference to `_imp___ZN11VlcInstanceC1ERK11QStringListP7QObject'
CMakeFiles\Test_CoreInstance.dir/objects.a(TestInstance.cpp.obj):TestInstance.cpp:(.text+0x459): undefined reference to `_imp___ZN11VlcInstance11setLogLevelEN3Vlc8LogLevelE'
CMakeFiles\Test_CoreInstance.dir/objects.a(TestInstance.cpp.obj):TestInstance.cpp:(.text+0x468): undefined reference to `_imp___ZNK11VlcInstance6statusEv'
CMakeFiles\Test_CoreInstance.dir/objects.a(TestInstance.cpp.obj):TestInstance.cpp:(.text+0x513): undefined reference to `_imp___ZN9VlcCommon4argsEv'
CMakeFiles\Test_CoreInstance.dir/objects.a(TestInstance.cpp.obj):TestInstance.cpp:(.text+0x531): undefined reference to `_imp___ZN11VlcInstanceC1ERK11QStringListP7QObject'
CMakeFiles\Test_CoreInstance.dir/objects.a(TestInstance.cpp.obj):TestInstance.cpp:(.text+0x544): undefined reference to `_imp___ZN11VlcInstance15libVersionMinorEv'
CMakeFiles\Test_CoreInstance.dir/objects.a(TestInstance.cpp.obj):TestInstance.cpp:(.text+0x54d): undefined reference to `_imp___ZN11VlcInstance15libVersionMajorEv'
CMakeFiles\Test_CoreInstance.dir/objects.a(TestInstance.cpp.obj):TestInstance.cpp:(.text+0x55b): undefined reference to `_imp___ZN11VlcInstance10libVersionEv'
CMakeFiles\Test_CoreInstance.dir/objects.a(TestInstance.cpp.obj):TestInstance.cpp:(.text+0x621): undefined reference to `_imp___ZN11VlcInstance8compilerEv'
CMakeFiles\Test_CoreInstance.dir/objects.a(TestInstance.cpp.obj):TestInstance.cpp:(.text+0x62a): undefined reference to `_imp___ZN11VlcInstance9changesetEv'
CMakeFiles\Test_CoreInstance.dir/objects.a(TestInstance.cpp.obj):TestInstance.cpp:(.text+0x636): undefined reference to `_imp___ZN11VlcInstance7versionEv'
CMakeFiles\Test_CoreInstance.dir/objects.a(TestInstance.cpp.obj):TestInstance.cpp:(.text+0x8d3): undefined reference to `_imp___ZN9VlcCommon4argsEv'
CMakeFiles\Test_CoreInstance.dir/objects.a(TestInstance.cpp.obj):TestInstance.cpp:(.text+0x8f0): undefined reference to `_imp___ZN11VlcInstanceC1ERK11QStringListP7QObject'
CMakeFiles\Test_CoreInstance.dir/objects.a(TestInstance.cpp.obj):TestInstance.cpp:(.text+0x93a): undefined reference to `_imp___ZN11VlcInstance12setUserAgentERK7QStringS2_'
CMakeFiles\Test_CoreInstance.dir/objects.a(TestInstance.cpp.obj):TestInstance.cpp:(.text+0xa23): undefined reference to `_imp___ZN9VlcCommon4argsEv'
CMakeFiles\Test_CoreInstance.dir/objects.a(TestInstance.cpp.obj):TestInstance.cpp:(.text+0xa40): undefined reference to `_imp___ZN11VlcInstanceC1ERK11QStringListP7QObject'
CMakeFiles\Test_CoreInstance.dir/objects.a(TestInstance.cpp.obj):TestInstance.cpp:(.text+0xaa5): undefined reference to `_imp___ZN11VlcInstance8setAppIdERK7QStringS2_S2_'
CMakeFiles\Test_CoreInstance.dir/objects.a(TestInstance.cpp.obj):TestInstance.cpp:(.text+0xbd3): undefined reference to `_imp___ZN9VlcCommon4argsEv'
CMakeFiles\Test_CoreInstance.dir/objects.a(TestInstance.cpp.obj):TestInstance.cpp:(.text+0xbf0): undefined reference to `_imp___ZN11VlcInstanceC1ERK11QStringListP7QObject'
CMakeFiles\Test_CoreInstance.dir/objects.a(TestInstance.cpp.obj):TestInstance.cpp:(.text+0xc05): undefined reference to `_imp___ZNK11VlcInstance15audioFilterListEv'
CMakeFiles\Test_CoreInstance.dir/objects.a(TestInstance.cpp.obj):TestInstance.cpp:(.text+0xc27): undefined reference to `_imp___ZNK11VlcInstance15videoFilterListEv'
CMakeFiles\Test_CoreInstance.dir/objects.a(TestInstance.cpp.obj):TestInstance.cpp:(.text+0xd17): undefined reference to `_imp___ZN11VlcInstanceC1ERK11QStringListP7QObject'
CMakeFiles\Test_CoreInstance.dir/objects.a(TestInstance.cpp.obj):TestInstance.cpp:(.text+0xd26): undefined reference to `_imp___ZNK11VlcInstance6statusEv'
CMakeFiles\Test_CoreInstance.dir/objects.a(TestsCommon.cpp.obj):TestsCommon.cpp:(.text+0x58): undefined reference to `_imp___ZN9VlcCommon13setPluginPathERK7QString'
CMakeFiles\Test_CoreInstance.dir/objects.a(TestsCommon.cpp.obj):TestsCommon.cpp:(.text+0x75): undefined reference to `_imp___ZN9VlcCommon4argsEv'
CMakeFiles\Test_CoreInstance.dir/objects.a(TestsCommon.cpp.obj):TestsCommon.cpp:(.text+0x92): undefined reference to `_imp___ZN11VlcInstanceC1ERK11QStringListP7QObject'
CMakeFiles\Test_CoreInstance.dir/objects.a(TestsCommon.cpp.obj):TestsCommon.cpp:(.text+0xaf): undefined reference to `_imp___ZN11VlcInstance11setLogLevelEN3Vlc8LogLevelE'
collect2.exe: error: ld returned 1 exit status
tests\core\CMakeFiles\Test_CoreInstance.dir\build.make:125: recipe for target 'tests/core/Test_CoreInstance.exe' failed
mingw32-make[2]: *** [tests/core/Test_CoreInstance.exe] Error 1
mingw32-make[2]: Leaving directory 'C:/QtProjects/Resources/vlc-qt/vlc-qt/build'
CMakeFiles\Makefile2:532: recipe for target 'tests/core/CMakeFiles/Test_CoreInstance.dir/all' failed
mingw32-make[1]: *** [tests/core/CMakeFiles/Test_CoreInstance.dir/all] Error 2
mingw32-make[1]: Leaving directory 'C:/QtProjects/Resources/vlc-qt/vlc-qt/build'
Makefile:142: recipe for target 'all' failed
mingw32-make: *** [all] Error 2
