### ISSUE TITLE
Does not build on Debian 8 (jessie) with GCC 4.9.2 without -std=c++11

### ISSUE THREAD

**Issue by Talkless** [vlc-qt/vlc-qt#225]
Trying to build 1.1.1 tag produced these error `‘shared_ptr’ in namespace ‘std’ does not name a template type`:
```
n file included from /home/vincas/code/opensource/vlc-qt/vlc-qt.git/src/core/AbstractVideoFrame.cpp:22:0:
/home/vincas/code/opensource/vlc-qt/vlc-qt.git/src/core/AbstractVideoFrame.h:70:40: error: ‘shared_ptr’ in namespace ‘std’ does not name a template typ
e
     void setPitchesAndLines(const std::shared_ptr<VlcAbstractVideoFrame> &frame);
                                        ^
/usr/bin/cmake -E cmake_progress_report /home/vincas/code/opensource/vlc-qt/vlc-qt.git/build/CMakeFiles 10
/home/vincas/code/opensource/vlc-qt/vlc-qt.git/src/core/AbstractVideoFrame.h:70:50: error: expected ‘,’ or ‘...’ before ‘<’ token
     void setPitchesAndLines(const std::shared_ptr<VlcAbstractVideoFrame> &frame);
                                                  ^
[ 26%] /home/vincas/code/opensource/vlc-qt/vlc-qt.git/src/core/AbstractVideoFrame.cpp:64:59: error: ‘shared_ptr’ in namespace ‘std’ does not name a tem
plate type
 void VlcAbstractVideoFrame::setPitchesAndLines(const std::shared_ptr<VlcAbstractVideoFrame> &frame)
                                                           ^
/home/vincas/code/opensource/vlc-qt/vlc-qt.git/src/core/AbstractVideoFrame.cpp:64:69: error: expected ‘,’ or ‘...’ before ‘<’ token
 void VlcAbstractVideoFrame::setPitchesAndLines(const std::shared_ptr<VlcAbstractVideoFrame> &frame)
                                                                     ^
/home/vincas/code/opensource/vlc-qt/vlc-qt.git/src/core/AbstractVideoFrame.cpp: In member function ‘void VlcAbstractVideoFrame::setPitchesAndLines(int)
’:
/home/vincas/code/opensource/vlc-qt/vlc-qt.git/src/core/AbstractVideoFrame.cpp:72:25: error: ‘frame’ was not declared in this scope
         planeSizes[i] = frame->planeSizes[i];
                         ^
```

GCC on Jessie does not have C++11 enabled by default, I've managed to workaround it by adding:
```
set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -std=c++11")
```
Into CMakeLists.txt.

Not sure if you should care about Debian Oldstable though.
